image: node:8.10.0

stages:
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - docker info

test_components:
  stage: test
  image: .
  script:
    - npm install
    - npm run test:component
