image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
#  - release
#  - deploy

variables:
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
  - docker build --pull -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE

test_components:
  stage: test
  script:
  - docker pull $CONTAINER_TEST_IMAGE
  - docker run $CONTAINER_TEST_IMAGE npm run test:component
#  - docker build -t my-docker-image .
#  - docker run my-docker-image npm run test:component

#image: node:8.10.0
#
#stages:
#  - test
#
## This folder is cached between builds
## http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#cache:
#  paths:
#    - node_modules/
#
#before_script:
#  - docker info
#
#test_components:
#  stage: test
#  image: .
#  script:
#    - npm install
#    - npm run test:component
