image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - review
#  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

lint:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE npm run lint

test-components:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE npm run test:component -- --coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  when: manual
  only:
    - master

deploy_review:
  stage: review
  environment:
    name: review
    url: http://devel7.sedis.ufrn.br/produtiivo/app/current
  variables:
    RELEASE_DIR: $REMOTE_APP_DIR/releases
    NEW_RELEASE_DIR: $REMOTE_APP_DIR/releases/$CI_COMMIT_SHA
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY");
    - ssh -o StrictHostKeyChecking=no rayron@"$REVIEW_SERVER" '[ -d '"'$RELEASE_DIR'"' ] || mkdir '"'$RELEASE_DIR'"' &&

      echo -e "--->  Clonando o repositório\n" &&
      git clone --depth 1 '"'$CI_REPOSITORY_URL'"' '"'$NEW_RELEASE_DIR'"' &&

      echo -e "--->  Instalando dependências\n" &&
      cd '"'$NEW_RELEASE_DIR'"' && npm install &&

      echo -e "--->  Gerando .env\n" &&
      echo API_URL=http://devel7.sedis.ufrn.br/produtiivo-ws/public/api/ >> .env &&
      echo UMI_ENV=dev >> .env &&

      echo -e "--->  Gerando build\n" &&
      npm run build &&

      echo -e "--->  Limpando build\n" &&
      find . -mindepth 1 -name "dist" -prune -o -print0 | xargs -0 rm -rf &&

      echo -e "--->  Colocando nova release em produção\n" &&
      ln -nfs '"'$NEW_RELEASE_DIR'"'/dist '"'$REMOTE_APP_DIR'"'/current &&
      cd '"'$REMOTE_APP_DIR'"' && cp .htaccess ./current/.htaccess'
  when: manual

#deploy:
#  stage: deploy
#  script:
#    - ./deploy.sh
#  only:
#    - master
