# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: ant design pro

trigger:
  batch: true
  branches:
    exclude:
      - gh-pages

jobs:
  - job: lintAndBuild

    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        fetchDepth: 1
        clean: false
      - script: yarn install
        displayName: install
      - script: npm run lint
        displayName: lint
      - script: npm run build
        displayName: build

  - job: test
    pool:
      vmImage: 'Ubuntu-16.04'

    container:
      image: circleci/node:latest-browsers
      options: '-u root'

    steps:
      - checkout: self
        fetchDepth: 1
        clean: false
      - script: yarn install
        displayName: install
      - script: npm run test:all
        displayName: test

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - checkout: self
        fetchDepth: 1
        clean: false
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: yarn install
        displayName: install
      - script: npm run lint
        displayName: lint
      - script: npm run build
        displayName: build

  - job: MacOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - checkout: self
        fetchDepth: 1
        clean: false
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: yarn install
        displayName: install
      - script: npm run lint
        displayName: lint
      - script: npm run build
        displayName: build
