version: "3.5"

services:
  ant-design-pro_dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: "ant-design-pro_dev"
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
      - ./mock:/usr/src/app/mock
